first = ['arise', 'awake', 'be', 'bear', 'bear', 'become', 'begin', 'bend', 'bind', 'bite', 
         'bleed', 'blow', 'break', 'breed', 'bring', 'broadcast', 'build', 'burn', 'burst', 
         'buy', 'cast', 'catch', 'choose', 'cling', 'come', 'cost', 'creep', 'cut', 'deal', 
         'dig', 'do', 'draw', 'dream', 'drink', 'drive', 'dwell', 'eat', 'fall', 'feed', 
         'feel', 'fight', 'find', 'flee', 'fling', 'fly', 'forbid', 'forget', 'forgive', 
         'freeze', 'get', 'give', 'go', 'grow', 'hang', 'have', 'hear', 'hide', 'hit', 
         'hold', 'hurt', 'keep', 'kneel', 'knit', 'lay', 'lead', 'lean', 'leap', 'learn', 
         'leave', 'lend', 'let', 'lie', 'light', 'lose', 'make', 'mean', 'meet', 'pay', 'put', 
         'read', 'ride', 'ring', 'rise', 'run', 'saw', 'say', 'see', 'seek', 'sell', 'send', 
         'set', 'shake', 'shed', 'shine', 'shoot', 'show', 'shrink', 'shut', 'sing', 'sink', 
         'sit', 'sleep', 'slide', 'smell', 'speak', 'speed', 'spell', 'spend', 'spill', 'spit', 
         'split', 'spoil', 'spread', 'spring', 'stand', 'steal', 'stick', 'sting', 'strike', 
         'strive', 'swear', 'sweep', 'swell', 'swim', 'swing', 'take', 'teach', 'tear', 'tell', 
         'think', 'throw', 'understand', 'wake', 'wear', 'weep', 'win', 'wind', 'write', ]


second = ['arose', 'awoke', '(was / were)', 'bore', 'bore', 'became', 'began', 'bent', 
          'bound', 'bit', 'bled', 'blew', 'broke', 'bred', 'brought', 'broadcast', 
          'built', 'burnt', 'burst', 'bought', 'cast', 'caught', 'chose', 'clung', 
          'came', 'cost', 'crept', 'cut', 'dealt', 'dug', 'did', 'drew', '(dreamt / dreamed)', 
          'drank', 'drove', 'dwelt', 'ate', 'fell', 'fed', 'felt', 'fought', 
          'found', 'fled', 'flung', 'flew', 'forbade', 'forgot', 'forgave', 'froze', 
          'got', 'gave', 'went', 'grew', 'hung', 'had', 'heard', 'hid', 'hit', 'held', 
          'hurt', 'kept', 'knelt', '(knit / knitted)', 'laid', 'led', 'leant', 'leapt', 
          'learned', 'left', 'lent', 'let', 'lay', 'lit', 'lost', 'made', 'meant', 'met', 
          'paid', 'put', 'read', 'rode', 'rang', 'rose', 'ran', 'sawed', 'said', 'saw', 
          'sought', 'sold', 'sent', 'set', 'shook', 'shed', 'shone', 'shot', 'showed', 'shrank', 
          'shut', 'sang', 'sank', 'sat', 'slept', 'slid', 'smelt', 'spoke', 'sped', 'spelt', 
          'spent', 'spilt', 'spat', 'split', 'spoilt', 'spread', 'sprang', 'stood', 'stole', 
          'stuck', 'stung', 'struck', 'strove', 'swore', 'swept', 'swelled', 'swam', 'swung', 
          'took', 'taught', 'tore', 'told', 'thought', 'threw', 'understood', 'woke', 'wore', 
          'wept', 'won', 'wound', 'wrote', ]


third = ['arisen', 'awoken', 'been', 'born', 'borne', 'become', 'begun', 'bent', 
         'bound', 'bitten', 'bled', 'blown', 'broken', 'bred', 'brought', 'broadcast', 
         'built', 'burnt', 'burst', 'bought', 'cast', 'caught', 'chosen', 'clung', 
         'come', 'cost', 'crept', 'cut', 'dealt', 'dug', 'done', 'drawn', '(dreamt / dreamed)', 
         'drunk', 'driven', 'dwelt', 'eaten', 'fallen', 'fed', 'felt', 'fought', 'found', 'fled', 
         'flung', 'flown', 'forbidden', 'forgotten', 'forgiven', 'frozen', 'got', 'given', 
         'gone', 'grown', 'hung', 'had', 'heard', 'hidden', 'hit', 'held', 'hurt', 'kept', 
         'knelt', '(knit / knitted)', 'laid', 'led', 'leant', 'leapt', 'learned', 'left', 
         'lent', 'let', 'lain', 'lit', 'lost', 'made', 'meant', 'met', 'paid', 'put', 
         'read', 'ridden', 'rung', 'risen', 'run', 'sawn', 'said', 'seen', 'sought', 
         'sold', 'sent', 'set', 'shaken', 'shed', 'shone', 'shot', 'shown', 'shrunk', 'shut', 
         'sung', 'sunk', 'sat', 'slept', 'slid', 'smelt', 'spoken', 'sped', 'spelt', 'spent', 
         'spilt', 'spat', 'split', 'spoilt', 'spread', 'sprung', 'stood', 'stolen', 'stuck', 
         'stung', 'struck', 'striven', 'sworn', 'swept', 'swollen', 'swum', 'swung', 'taken', 
         'taught', 'torn', 'told', 'thought', 'thrown', 'understood', 'woken', 'worn', 'wept', 
         'won', 'wound', 'written', ]


translate = ['возникать', '(просыпаться / будить)', '(быть / вляться / находиться)', 'рождать', 
             'выносить', 'становиться', '(начинать / -ся)', '(гнуть / -ся)', 'связывать', 
             'кусать', 'кровоточить', 'дуть', 'ломать', '(вырастить / воспитать)', 'приносить', 
             'транслировать', 'строить', '(гореть / жечь)', 'разрываться', 'покупать', 
             '(бросать / кидать)', '(ловить / схватить / поймать)', 'выбирать', 
             '(прилипать / цепляться)', 'приходить', 'стоить', 'ползать', 'резать', '(иметь дело / торговать)', 
             'копать', 'делать', '(рисовать / тащить / составлять)', '(мечтать / видеть сны)', 'пить', 
             '(ехать / везти / гнать)', '(обитать / останавливаться / подробно)', 'есть (принимать пищу)', 
             'падать', 'кормить', 'чувствовать', '(драться / сражаться / бороться)', 'находить', 
             '(бежать / спасаться бегством)', 'кидать', 'летать', 'запрещать', 'забывать', 'прощать', 
             '(замерзать / замораживать)', '(получать / становиться)', 'давать', '(идти / ехать)', 
             '(расти / становиться)', '(висеть / вешать)', 'иметь', 'слышать', 'прятать', '(ударять / поражать)', 
             'держать', '(повредить / ушибить)', '(держать / хранить)', 'становиться на колени', 'вязать', 
             'класть', 'вести', 'прислоняться', 'прыгать', 'учиться', '(оставлять / уезжать)', 'давать взаймы', 
             '(позволять / сдавать внаём)', 'лежать', '(зажигать / освещать)', 'терять', 
             '(делать / заставлять)', '(значить / подразумевать)', 'встречать', 'платить', 
             '(помещать / класть)', 'читать', '(ездить / кататься)', '(звонить / звенеть)', 
             'подниматься', 'бежать', 'пилить', '(говорить / сказать)', 'видеть', 'искать', 'продавать', 
             'посылать', '(помещать / ставить)', 'трясти', 'проливать (слёзы, кровь)', '(сиять / светить)', 
             'стрелять', 'показывать', 'сморщиваться', 'закрывать', 'петь', '(тонуть / погружаться)', 
             'сидеть', 'спать', 'скользить', '(пахнуть / нюхать)', 'говорить', '(спешить / ускорять)', 
             'произносить по буквам', 'тратить', 'проливать', 'плевать', '(раскалывать / -ся)', 'портить', 
             '(распространять / - ся)', 'прыгать', 'стоять', 'красть', '(приклеивать / -ся)', 'жалить', 
             '(ударять / бастовать)', 'стремиться', 'клясться; браниться', 'мести', '(пухнуть / раздуваться)', 
             'плавать', '(качать / –ся / размахивать)', 'брать', 'учить', 'рвать', 'рассказывать', 'думать', 
             'бросать', 'понимать', '(будить / просыпаться)', 'носить', 'плакать', 'выигрывать', 
             '(заводить (часы) / виться)', 'писать', ]
