first = ['to arise', 'to awake', 'to be', 'to bear', 'to bear', 'to become', 
         'to begin', 'to bend', 'to bind', 'to bite', 'to bleed', 'to blow', 
         'to break', 'to breed', 'to bring', 'to broadcast', 'to build', 'to burn', 
         'to burst', 'to buy', 'to cast', 'to catch', 'to choose', 'to cling', 'to come', 
         'to cost', 'to creep', 'to cut', 'to deal', 'to dig', 'to do', 'to draw', 
         'to dream', 'to drink', 'to drive', 'to dwell', 'to eat', 'to fall', 'to feed', 
         'to feel', 'to fight', 'to find', 'to flee', 'to fling', 'to fly', 'to forbid', 
         'to forget', 'to forgive', 'to freeze', 'to get', 'to give', 'to go', 'to grow', 
         'to hang', 'to have', 'to hear', 'to hide', 'to hit', 'to hold', 'to hurt', 'to keep', 
         'to kneel', 'to knit', 'to lay', 'to lead', 'to lean', 'to leap', 'to learn', 'to leave', 
         'to lend', 'to let', 'to lie', 'to light', 'to lose', 'to make', 'to mean', 'to meet', 
         'to pay', 'to put', 'to read', 'to ride', 'to ring', 'to rise', 'to run', 'to saw', 
         'to say', 'to see', 'to seek', 'to sell', 'to send', 'to set', 'to shake', 'to shed', 
         'to shine', 'to shoot', 'to show', 'to shrink', 'to shut', 'to sing', 'to sink', 
         'to sit', 'to sleep', 'to slide', 'to smell', 'to speak', 'to speed', 'to spell', 
         'to spend', 'to spill', 'to spit', 'to split', 'to spoil', 'to spread', 'to spring', 
         'to stand', 'to steal', 'to stick', 'to sting', 'to strike', 'to strive', 'to swear', 
         'to sweep', 'to swell', 'to swim', 'to swing', 'to take', 'to teach', 'to tear', 'to tell', 
         'to think', 'to throw', 'to understand', 'to wake', 'to wear', 'to weep', 'to win', 
         'to wind', 'to write', ]


second = ['arose', 'awoke', '(was / were)', 'bore', 'bore', 'became', 'began', 'bent', 
          'bound', 'bit', 'bled', 'blew', 'broke', 'bred', 'brought', 'broadcast', 
          'built', 'burnt', 'burst', 'bought', 'cast', 'caught', 'chose', 'clung', 
          'came', 'cost', 'crept', 'cut', 'dealt', 'dug', 'did', 'drew', '(dreamt / dreamed)', 
          'drank', 'drove', 'dwelt', 'ate', 'fell', 'fed', 'felt', 'fought', 
          'found', 'fled', 'flung', 'flew', 'forbade', 'forgot', 'forgave', 'froze', 
          'got', 'gave', 'went', 'grew', 'hung', 'had', 'heard', 'hid', 'hit', 'held', 
          'hurt', 'kept', 'knelt', '(knit / knitted)', 'laid', 'led', 'leant', 'leapt', 
          'learned', 'left', 'lent', 'let', 'lay', 'lit', 'lost', 'made', 'meant', 'met', 
          'paid', 'put', 'read', 'rode', 'rang', 'rose', 'ran', 'sawed', 'said', 'saw', 
          'sought', 'sold', 'sent', 'set', 'shook', 'shed', 'shone', 'shot', 'showed', 'shrank', 
          'shut', 'sang', 'sank', 'sat', 'slept', 'slid', 'smelt', 'spoke', 'sped', 'spelt', 
          'spent', 'spilt', 'spat', 'split', 'spoilt', 'spread', 'sprang', 'stood', 'stole', 
          'stuck', 'stung', 'struck', 'strove', 'swore', 'swept', 'swelled', 'swam', 'swung', 
          'took', 'taught', 'tore', 'told', 'thought', 'threw', 'understood', 'woke', 'wore', 
          'wept', 'won', 'wound', 'wrote', ]


third = ['arisen', 'awoken', 'been', 'born', 'borne', 'become', 'begun', 'bent', 
         'bound', 'bitten', 'bled', 'blown', 'broken', 'bred', 'brought', 'broadcast', 
         'built', 'burnt', 'burst', 'bought', 'cast', 'caught', 'chosen', 'clung', 
         'come', 'cost', 'crept', 'cut', 'dealt', 'dug', 'done', 'drawn', '(dreamt / dreamed)', 
         'drunk', 'driven', 'dwelt', 'eaten', 'fallen', 'fed', 'felt', 'fought', 'found', 'fled', 
         'flung', 'flown', 'forbidden', 'forgotten', 'forgiven', 'frozen', 'got', 'given', 
         'gone', 'grown', 'hung', 'had', 'heard', 'hidden', 'hit', 'held', 'hurt', 'kept', 
         'knelt', '(knit / knitted)', 'laid', 'led', 'leant', 'leapt', 'learned', 'left', 
         'lent', 'let', 'lain', 'lit', 'lost', 'made', 'meant', 'met', 'paid', 'put', 
         'read', 'ridden', 'rung', 'risen', 'run', 'sawn', 'said', 'seen', 'sought', 
         'sold', 'sent', 'set', 'shaken', 'shed', 'shone', 'shot', 'shown', 'shrunk', 'shut', 
         'sung', 'sunk', 'sat', 'slept', 'slid', 'smelt', 'spoken', 'sped', 'spelt', 'spent', 
         'spilt', 'spat', 'split', 'spoilt', 'spread', 'sprung', 'stood', 'stolen', 'stuck', 
         'stung', 'struck', 'striven', 'sworn', 'swept', 'swollen', 'swum', 'swung', 'taken', 
         'taught', 'torn', 'told', 'thought', 'thrown', 'understood', 'woken', 'worn', 'wept', 
         'won', 'wound', 'written', ]

translate = ['возникать', '(просыпаться / будить)', '(быть / вляться / находиться)', 'рождать', 
             'выносить', 'становиться', '(начинать / -ся)', '(гнуть / -ся)', 'связывать', 
             'кусать', 'кровоточить', 'дуть', 'ломать', '(вырастить / воспитать)', 'приносить', 
             'транслировать', 'строить', '(гореть / жечь)', 'разрываться', 'покупать', 
             '(бросать / кидать)', '(ловить / схватить / поймать)', 'выбирать', 
             '(прилипать / цепляться)', 'приходить', 'стоить', 'ползать', 'резать', 
             '(иметь дело / торговать)', 'копать', 'делать', '(рисовать / тащить / составлять)', 
             '(мечтать / видеть сны)', 'пить', '(ехать / везти / гнать)', '(обитать / останавливаться)', 
             'подробно', 'есть (принимать пищу)', 'падать', 'кормить', 'чувствовать', 
             '(драться / сражаться / бороться)', 'находить', '(бежать / спасаться бегством)', 
             'кидать', 'летать', 'запрещать', 'забывать', 'прощать', '(замерзать / замораживать получать / становиться)', 
             'давать', '(идти / ехать)', '(расти / становиться)', '(висеть / вешать)', 'иметь', 
             'слышать', 'прятать', '(ударять / поражать)', 'держать', '(повредить / ушибить)', 
             '(держать / хранить)', 'становиться на колени', 'вязать', 'класть', 'вести', 
             'прислоняться', 'прыгать', 'учиться', '(оставлять / уезжать)', 'давать взаймы', 
             '(позволять / сдавать внаём)', 'лежать', '(зажигать / освещать)', 'терять', 
             '(делать / заставлять)', '(значить / подразумевать)', 'встречать', 'платить', 
             '(помещать / класть)', 'читать', '(ездить / кататься)', '(звонить / звенеть)', 
             'подниматься', 'бежать', 'пилить', '(говорить / сказать)', 'видеть', 'искать', 'продавать', 
             'посылать', '(помещать / ставить)', 'трясти', 'проливать (слёзы, кровь)', '(сиять / светить)', 
             'стрелять', 'показывать', 'сморщиваться', 'закрывать', 'петь', '(тонуть / погружаться)', 
             'сидеть', 'спать', 'скользить', '(пахнуть / нюхать)', 'говорить', '(спешить / ускорять)', 
             'произносить по буквам', 'тратить', 'проливать', 'плевать', '(раскалывать / -ся)', 'портить', 
             '(распространять / - ся)', 'прыгать', 'стоять', 'красть', '(приклеивать / -ся)', 'жалить', 
             '(ударять / бастовать)', 'стремиться', 'клясться; браниться', 'мести', '(пухнуть / раздуваться)', 
             'плавать', '(качать / –ся / размахивать)', 'брать', 'учить', 'рвать', 'рассказывать', 'думать', 
             'бросать', 'понимать', '(будить / просыпаться)', 'носить', 'плакать', 'выигрывать', 
             '(заводить (часы) / виться)', 'писать', ]
             
